/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Meli Honeypot Command Center API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface DashboardSummary {
  eventsLast24h: number;
  /** @nullable */
  eventsChangePercent?: number | null;
  criticalAlerts: number;
  criticalUnacknowledged?: number;
  uniqueAttackers: number;
  attackersNewToday?: number;
  attackersDegraded?: number;
  honeypotsOnline: number;
  honeypotsTotal: number;
  lastStrikeIp: string;
  lastStrikeAt: string;
  strikesPerHour: number;
  peakStrikesPerHour: number;
  uptimeSeconds: number;
  ingestRatePerMin: number;
  dbSizeMb: number;
}

export interface SeverityBreakdown {
  critical: number;
  high: number;
  medium: number;
  low: number;
  info: number;
  total?: number;
}

export interface TopAttacker {
  rank: number;
  ip: string;
  country: string;
  countryCode?: string;
  /** @nullable */
  asn?: string | null;
  attackCount: number;
}

export interface IntensityPoint {
  hour: string;
  count: number;
}

export interface CapacityInfo {
  capacityPercent: number;
  totalCaptured: number;
  maxCapacity?: number;
}

export interface HoneypotService {
  id: number;
  name: string;
  protocol: string;
  port: number;
  status: string;
  eventsToday?: number;
  /** @nullable */
  lastSeen?: string | null;
}

export interface Event {
  id: number;
  timestamp: string;
  sourceIp: string;
  /** @nullable */
  sourceCountry?: string | null;
  /** @nullable */
  sourceCountryCode?: string | null;
  service: string;
  eventType: string;
  severity: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
  /** @nullable */
  command?: string | null;
  /** @nullable */
  payload?: string | null;
  /** @nullable */
  raw?: string | null;
}

export interface Attacker {
  id: number;
  ip: string;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  asn?: string | null;
  /** @nullable */
  org?: string | null;
  firstSeen: string;
  lastSeen: string;
  attackCount: number;
  isSticky?: boolean;
  /** @nullable */
  riskScore?: number | null;
}

export interface IpReputation {
  ip: string;
  /** @nullable */
  abuseConfidenceScore?: number | null;
  /** @nullable */
  isKnownAttacker?: boolean | null;
  /** @nullable */
  isTor?: boolean | null;
  /** @nullable */
  isVpn?: boolean | null;
  /** @nullable */
  isHosting?: boolean | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  org?: string | null;
  /** @nullable */
  greynoiseClassification?: string | null;
  /** @nullable */
  virusTotalPositives?: number | null;
  /** @nullable */
  shodanPorts?: string | null;
  /** @nullable */
  lastSeen?: string | null;
  sources?: string[];
}

export interface Credential {
  id: number;
  username: string;
  password: string;
  firstSeen: string;
  lastSeen?: string;
  count: number;
  service?: string;
}

export interface Command {
  id: number;
  command: string;
  timestamp: string;
  sourceIp: string;
  /** @nullable */
  session?: string | null;
  count?: number;
}

export interface Payload {
  id: number;
  filename: string;
  sha256: string;
  /** @nullable */
  md5?: string | null;
  firstSeen: string;
  lastSeen?: string;
  size: number;
  /** @nullable */
  mimeType?: string | null;
  /** @nullable */
  threatName?: string | null;
  downloadCount?: number;
}

export interface Session {
  id: number;
  sourceIp: string;
  /** @nullable */
  country?: string | null;
  startedAt: string;
  /** @nullable */
  endedAt?: string | null;
  duration: number;
  commandCount?: number;
  isSticky?: boolean;
  tarpitSeconds?: number;
}

export interface Alert {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  severity: string;
  createdAt: string;
  acknowledged: boolean;
  /** @nullable */
  acknowledgedAt?: string | null;
  /** @nullable */
  sourceIp?: string | null;
  /** @nullable */
  service?: string | null;
}

export interface Report {
  id: number;
  title: string;
  type: string;
  /** @nullable */
  summary?: string | null;
  createdAt: string;
  eventCount?: number;
  attackerCount?: number;
}

export interface Botnet {
  id: number;
  name: string;
  /** @nullable */
  family?: string | null;
  firstSeen: string;
  lastSeen?: string;
  nodeCount: number;
  c2Servers?: string[];
  targetedServices?: string[];
  riskLevel?: string;
}

export type ListEventsParams = {
limit?: number;
offset?: number;
severity?: string;
service?: string;
};

export type ListAttackersParams = {
limit?: number;
offset?: number;
search?: string;
};

export type ListCredentialsParams = {
limit?: number;
offset?: number;
};

export type ListCommandsParams = {
limit?: number;
offset?: number;
};

export type ListPayloadsParams = {
limit?: number;
offset?: number;
};

export type ListSessionsParams = {
limit?: number;
offset?: number;
};

export type ListAlertsParams = {
acknowledged?: boolean;
};

export type LookupIpReputationParams = {
ip: string;
};

