/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Meli Honeypot Command Center API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Alert,
  Attacker,
  Botnet,
  CapacityInfo,
  Command,
  Credential,
  DashboardSummary,
  Event,
  HealthStatus,
  HoneypotService,
  IntensityPoint,
  IpReputation,
  ListAlertsParams,
  ListAttackersParams,
  ListCommandsParams,
  ListCredentialsParams,
  ListEventsParams,
  ListPayloadsParams,
  ListSessionsParams,
  LookupIpReputationParams,
  Payload,
  Report,
  Session,
  SeverityBreakdown,
  TopAttacker
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardSummaryUrl = () => {




  return `/api/dashboard/summary`
}

/**
 * @summary KPI tiles and system status
 */
export const getDashboardSummary = async ( options?: RequestInit): Promise<DashboardSummary> => {

  return customFetch<DashboardSummary>(getGetDashboardSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardSummaryQueryKey = () => {
    return [
    `/api/dashboard/summary`
    ] as const;
    }


export const getGetDashboardSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSummary>>> = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSummary>>>
export type GetDashboardSummaryQueryError = ErrorType<unknown>


/**
 * @summary KPI tiles and system status
 */

export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardSeverityUrl = () => {




  return `/api/dashboard/severity`
}

/**
 * @summary Severity breakdown counts
 */
export const getDashboardSeverity = async ( options?: RequestInit): Promise<SeverityBreakdown> => {

  return customFetch<SeverityBreakdown>(getGetDashboardSeverityUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardSeverityQueryKey = () => {
    return [
    `/api/dashboard/severity`
    ] as const;
    }


export const getGetDashboardSeverityQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSeverity>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSeverity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardSeverityQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSeverity>>> = ({ signal }) => getDashboardSeverity({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardSeverity>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardSeverityQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSeverity>>>
export type GetDashboardSeverityQueryError = ErrorType<unknown>


/**
 * @summary Severity breakdown counts
 */

export function useGetDashboardSeverity<TData = Awaited<ReturnType<typeof getDashboardSeverity>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSeverity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardSeverityQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardTopAttackersUrl = () => {




  return `/api/dashboard/top-attackers`
}

/**
 * @summary Top attackers by event count
 */
export const getDashboardTopAttackers = async ( options?: RequestInit): Promise<TopAttacker[]> => {

  return customFetch<TopAttacker[]>(getGetDashboardTopAttackersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardTopAttackersQueryKey = () => {
    return [
    `/api/dashboard/top-attackers`
    ] as const;
    }


export const getGetDashboardTopAttackersQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardTopAttackers>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardTopAttackers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardTopAttackersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardTopAttackers>>> = ({ signal }) => getDashboardTopAttackers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardTopAttackers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardTopAttackersQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardTopAttackers>>>
export type GetDashboardTopAttackersQueryError = ErrorType<unknown>


/**
 * @summary Top attackers by event count
 */

export function useGetDashboardTopAttackers<TData = Awaited<ReturnType<typeof getDashboardTopAttackers>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardTopAttackers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardTopAttackersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardIntensityUrl = () => {




  return `/api/dashboard/intensity`
}

/**
 * @summary 24h attack intensity chart data
 */
export const getDashboardIntensity = async ( options?: RequestInit): Promise<IntensityPoint[]> => {

  return customFetch<IntensityPoint[]>(getGetDashboardIntensityUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardIntensityQueryKey = () => {
    return [
    `/api/dashboard/intensity`
    ] as const;
    }


export const getGetDashboardIntensityQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardIntensity>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardIntensity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardIntensityQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardIntensity>>> = ({ signal }) => getDashboardIntensity({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardIntensity>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardIntensityQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardIntensity>>>
export type GetDashboardIntensityQueryError = ErrorType<unknown>


/**
 * @summary 24h attack intensity chart data
 */

export function useGetDashboardIntensity<TData = Awaited<ReturnType<typeof getDashboardIntensity>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardIntensity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardIntensityQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardHoneypotFleetUrl = () => {




  return `/api/dashboard/honeypot-fleet`
}

/**
 * @summary Honeypot fleet status
 */
export const getDashboardHoneypotFleet = async ( options?: RequestInit): Promise<HoneypotService[]> => {

  return customFetch<HoneypotService[]>(getGetDashboardHoneypotFleetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardHoneypotFleetQueryKey = () => {
    return [
    `/api/dashboard/honeypot-fleet`
    ] as const;
    }


export const getGetDashboardHoneypotFleetQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardHoneypotFleet>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardHoneypotFleet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardHoneypotFleetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardHoneypotFleet>>> = ({ signal }) => getDashboardHoneypotFleet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardHoneypotFleet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardHoneypotFleetQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardHoneypotFleet>>>
export type GetDashboardHoneypotFleetQueryError = ErrorType<unknown>


/**
 * @summary Honeypot fleet status
 */

export function useGetDashboardHoneypotFleet<TData = Awaited<ReturnType<typeof getDashboardHoneypotFleet>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardHoneypotFleet>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardHoneypotFleetQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardCapacityUrl = () => {




  return `/api/dashboard/capacity`
}

/**
 * @summary Honey jar capacity (% full)
 */
export const getDashboardCapacity = async ( options?: RequestInit): Promise<CapacityInfo> => {

  return customFetch<CapacityInfo>(getGetDashboardCapacityUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardCapacityQueryKey = () => {
    return [
    `/api/dashboard/capacity`
    ] as const;
    }


export const getGetDashboardCapacityQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardCapacity>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardCapacity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardCapacityQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardCapacity>>> = ({ signal }) => getDashboardCapacity({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardCapacity>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardCapacityQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardCapacity>>>
export type GetDashboardCapacityQueryError = ErrorType<unknown>


/**
 * @summary Honey jar capacity (% full)
 */

export function useGetDashboardCapacity<TData = Awaited<ReturnType<typeof getDashboardCapacity>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardCapacity>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardCapacityQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListEventsUrl = (params?: ListEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/events?${stringifiedParams}` : `/api/events`
}

/**
 * @summary List recent honeypot events
 */
export const listEvents = async (params?: ListEventsParams, options?: RequestInit): Promise<Event[]> => {

  return customFetch<Event[]>(getListEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEventsQueryKey = (params?: ListEventsParams,) => {
    return [
    `/api/events`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEventsQueryOptions = <TData = Awaited<ReturnType<typeof listEvents>>, TError = ErrorType<unknown>>(params?: ListEventsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEvents>>> = ({ signal }) => listEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData> & { queryKey: QueryKey }
}

export type ListEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listEvents>>>
export type ListEventsQueryError = ErrorType<unknown>


/**
 * @summary List recent honeypot events
 */

export function useListEvents<TData = Awaited<ReturnType<typeof listEvents>>, TError = ErrorType<unknown>>(
 params?: ListEventsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListEventsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetEventUrl = (id: number,) => {




  return `/api/events/${id}`
}

/**
 * @summary Get event by ID
 */
export const getEvent = async (id: number, options?: RequestInit): Promise<Event> => {

  return customFetch<Event>(getGetEventUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEventQueryKey = (id: number,) => {
    return [
    `/api/events/${id}`
    ] as const;
    }


export const getGetEventQueryOptions = <TData = Awaited<ReturnType<typeof getEvent>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvent>>> = ({ signal }) => getEvent(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData> & { queryKey: QueryKey }
}

export type GetEventQueryResult = NonNullable<Awaited<ReturnType<typeof getEvent>>>
export type GetEventQueryError = ErrorType<unknown>


/**
 * @summary Get event by ID
 */

export function useGetEvent<TData = Awaited<ReturnType<typeof getEvent>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetEventQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListAttackersUrl = (params?: ListAttackersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/attackers?${stringifiedParams}` : `/api/attackers`
}

/**
 * @summary List attackers
 */
export const listAttackers = async (params?: ListAttackersParams, options?: RequestInit): Promise<Attacker[]> => {

  return customFetch<Attacker[]>(getListAttackersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAttackersQueryKey = (params?: ListAttackersParams,) => {
    return [
    `/api/attackers`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAttackersQueryOptions = <TData = Awaited<ReturnType<typeof listAttackers>>, TError = ErrorType<unknown>>(params?: ListAttackersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAttackers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAttackersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAttackers>>> = ({ signal }) => listAttackers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAttackers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAttackersQueryResult = NonNullable<Awaited<ReturnType<typeof listAttackers>>>
export type ListAttackersQueryError = ErrorType<unknown>


/**
 * @summary List attackers
 */

export function useListAttackers<TData = Awaited<ReturnType<typeof listAttackers>>, TError = ErrorType<unknown>>(
 params?: ListAttackersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAttackers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAttackersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAttackerUrl = (id: number,) => {




  return `/api/attackers/${id}`
}

/**
 * @summary Get attacker by ID
 */
export const getAttacker = async (id: number, options?: RequestInit): Promise<Attacker> => {

  return customFetch<Attacker>(getGetAttackerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAttackerQueryKey = (id: number,) => {
    return [
    `/api/attackers/${id}`
    ] as const;
    }


export const getGetAttackerQueryOptions = <TData = Awaited<ReturnType<typeof getAttacker>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttacker>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttackerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttacker>>> = ({ signal }) => getAttacker(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttacker>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAttackerQueryResult = NonNullable<Awaited<ReturnType<typeof getAttacker>>>
export type GetAttackerQueryError = ErrorType<unknown>


/**
 * @summary Get attacker by ID
 */

export function useGetAttacker<TData = Awaited<ReturnType<typeof getAttacker>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttacker>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAttackerQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAttackerReputationUrl = (id: number,) => {




  return `/api/attackers/${id}/reputation`
}

/**
 * @summary IP reputation enrichment for attacker
 */
export const getAttackerReputation = async (id: number, options?: RequestInit): Promise<IpReputation> => {

  return customFetch<IpReputation>(getGetAttackerReputationUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAttackerReputationQueryKey = (id: number,) => {
    return [
    `/api/attackers/${id}/reputation`
    ] as const;
    }


export const getGetAttackerReputationQueryOptions = <TData = Awaited<ReturnType<typeof getAttackerReputation>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttackerReputation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttackerReputationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttackerReputation>>> = ({ signal }) => getAttackerReputation(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttackerReputation>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAttackerReputationQueryResult = NonNullable<Awaited<ReturnType<typeof getAttackerReputation>>>
export type GetAttackerReputationQueryError = ErrorType<unknown>


/**
 * @summary IP reputation enrichment for attacker
 */

export function useGetAttackerReputation<TData = Awaited<ReturnType<typeof getAttackerReputation>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAttackerReputation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAttackerReputationQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListCredentialsUrl = (params?: ListCredentialsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/credentials?${stringifiedParams}` : `/api/credentials`
}

/**
 * @summary List captured credentials
 */
export const listCredentials = async (params?: ListCredentialsParams, options?: RequestInit): Promise<Credential[]> => {

  return customFetch<Credential[]>(getListCredentialsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCredentialsQueryKey = (params?: ListCredentialsParams,) => {
    return [
    `/api/credentials`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCredentialsQueryOptions = <TData = Awaited<ReturnType<typeof listCredentials>>, TError = ErrorType<unknown>>(params?: ListCredentialsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCredentials>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCredentialsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCredentials>>> = ({ signal }) => listCredentials(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCredentials>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCredentialsQueryResult = NonNullable<Awaited<ReturnType<typeof listCredentials>>>
export type ListCredentialsQueryError = ErrorType<unknown>


/**
 * @summary List captured credentials
 */

export function useListCredentials<TData = Awaited<ReturnType<typeof listCredentials>>, TError = ErrorType<unknown>>(
 params?: ListCredentialsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCredentials>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCredentialsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListCommandsUrl = (params?: ListCommandsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/commands?${stringifiedParams}` : `/api/commands`
}

/**
 * @summary List captured SSH commands
 */
export const listCommands = async (params?: ListCommandsParams, options?: RequestInit): Promise<Command[]> => {

  return customFetch<Command[]>(getListCommandsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCommandsQueryKey = (params?: ListCommandsParams,) => {
    return [
    `/api/commands`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCommandsQueryOptions = <TData = Awaited<ReturnType<typeof listCommands>>, TError = ErrorType<unknown>>(params?: ListCommandsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCommands>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommandsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCommands>>> = ({ signal }) => listCommands(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCommands>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCommandsQueryResult = NonNullable<Awaited<ReturnType<typeof listCommands>>>
export type ListCommandsQueryError = ErrorType<unknown>


/**
 * @summary List captured SSH commands
 */

export function useListCommands<TData = Awaited<ReturnType<typeof listCommands>>, TError = ErrorType<unknown>>(
 params?: ListCommandsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCommands>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCommandsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListPayloadsUrl = (params?: ListPayloadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/payloads?${stringifiedParams}` : `/api/payloads`
}

/**
 * @summary List captured malware payloads
 */
export const listPayloads = async (params?: ListPayloadsParams, options?: RequestInit): Promise<Payload[]> => {

  return customFetch<Payload[]>(getListPayloadsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPayloadsQueryKey = (params?: ListPayloadsParams,) => {
    return [
    `/api/payloads`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPayloadsQueryOptions = <TData = Awaited<ReturnType<typeof listPayloads>>, TError = ErrorType<unknown>>(params?: ListPayloadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayloads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPayloadsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPayloads>>> = ({ signal }) => listPayloads(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPayloads>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPayloadsQueryResult = NonNullable<Awaited<ReturnType<typeof listPayloads>>>
export type ListPayloadsQueryError = ErrorType<unknown>


/**
 * @summary List captured malware payloads
 */

export function useListPayloads<TData = Awaited<ReturnType<typeof listPayloads>>, TError = ErrorType<unknown>>(
 params?: ListPayloadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPayloads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPayloadsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListServicesUrl = () => {




  return `/api/services`
}

/**
 * @summary List honeypot services
 */
export const listServices = async ( options?: RequestInit): Promise<HoneypotService[]> => {

  return customFetch<HoneypotService[]>(getListServicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListServicesQueryKey = () => {
    return [
    `/api/services`
    ] as const;
    }


export const getListServicesQueryOptions = <TData = Awaited<ReturnType<typeof listServices>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListServicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listServices>>> = ({ signal }) => listServices({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData> & { queryKey: QueryKey }
}

export type ListServicesQueryResult = NonNullable<Awaited<ReturnType<typeof listServices>>>
export type ListServicesQueryError = ErrorType<unknown>


/**
 * @summary List honeypot services
 */

export function useListServices<TData = Awaited<ReturnType<typeof listServices>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listServices>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListServicesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListSessionsUrl = (params?: ListSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sessions?${stringifiedParams}` : `/api/sessions`
}

/**
 * @summary List SSH tarpit sessions
 */
export const listSessions = async (params?: ListSessionsParams, options?: RequestInit): Promise<Session[]> => {

  return customFetch<Session[]>(getListSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListSessionsQueryKey = (params?: ListSessionsParams,) => {
    return [
    `/api/sessions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListSessionsQueryOptions = <TData = Awaited<ReturnType<typeof listSessions>>, TError = ErrorType<unknown>>(params?: ListSessionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSessionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) => listSessions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>
export type ListSessionsQueryError = ErrorType<unknown>


/**
 * @summary List SSH tarpit sessions
 */

export function useListSessions<TData = Awaited<ReturnType<typeof listSessions>>, TError = ErrorType<unknown>>(
 params?: ListSessionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListSessionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListAlertsUrl = (params?: ListAlertsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alerts?${stringifiedParams}` : `/api/alerts`
}

/**
 * @summary List security alerts
 */
export const listAlerts = async (params?: ListAlertsParams, options?: RequestInit): Promise<Alert[]> => {

  return customFetch<Alert[]>(getListAlertsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAlertsQueryKey = (params?: ListAlertsParams,) => {
    return [
    `/api/alerts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAlertsQueryOptions = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = ErrorType<unknown>>(params?: ListAlertsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAlertsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlerts>>> = ({ signal }) => listAlerts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAlertsQueryResult = NonNullable<Awaited<ReturnType<typeof listAlerts>>>
export type ListAlertsQueryError = ErrorType<unknown>


/**
 * @summary List security alerts
 */

export function useListAlerts<TData = Awaited<ReturnType<typeof listAlerts>>, TError = ErrorType<unknown>>(
 params?: ListAlertsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAlertsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getAcknowledgeAlertUrl = (id: number,) => {




  return `/api/alerts/${id}/acknowledge`
}

/**
 * @summary Acknowledge an alert
 */
export const acknowledgeAlert = async (id: number, options?: RequestInit): Promise<Alert> => {

  return customFetch<Alert>(getAcknowledgeAlertUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getAcknowledgeAlertMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acknowledgeAlert>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof acknowledgeAlert>>, TError,{id: number}, TContext> => {

const mutationKey = ['acknowledgeAlert'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acknowledgeAlert>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  acknowledgeAlert(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcknowledgeAlertMutationResult = NonNullable<Awaited<ReturnType<typeof acknowledgeAlert>>>

    export type AcknowledgeAlertMutationError = ErrorType<unknown>

    /**
 * @summary Acknowledge an alert
 */
export const useAcknowledgeAlert = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acknowledgeAlert>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof acknowledgeAlert>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getAcknowledgeAlertMutationOptions(options));
    }

export const getListReportsUrl = () => {




  return `/api/reports`
}

/**
 * @summary List intelligence reports
 */
export const listReports = async ( options?: RequestInit): Promise<Report[]> => {

  return customFetch<Report[]>(getListReportsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListReportsQueryKey = () => {
    return [
    `/api/reports`
    ] as const;
    }


export const getListReportsQueryOptions = <TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListReportsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listReports>>> = ({ signal }) => listReports({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData> & { queryKey: QueryKey }
}

export type ListReportsQueryResult = NonNullable<Awaited<ReturnType<typeof listReports>>>
export type ListReportsQueryError = ErrorType<unknown>


/**
 * @summary List intelligence reports
 */

export function useListReports<TData = Awaited<ReturnType<typeof listReports>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listReports>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListReportsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListBotnetsUrl = () => {




  return `/api/botnets`
}

/**
 * @summary List detected botnets
 */
export const listBotnets = async ( options?: RequestInit): Promise<Botnet[]> => {

  return customFetch<Botnet[]>(getListBotnetsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListBotnetsQueryKey = () => {
    return [
    `/api/botnets`
    ] as const;
    }


export const getListBotnetsQueryOptions = <TData = Awaited<ReturnType<typeof listBotnets>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBotnets>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBotnetsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBotnets>>> = ({ signal }) => listBotnets({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBotnets>>, TError, TData> & { queryKey: QueryKey }
}

export type ListBotnetsQueryResult = NonNullable<Awaited<ReturnType<typeof listBotnets>>>
export type ListBotnetsQueryError = ErrorType<unknown>


/**
 * @summary List detected botnets
 */

export function useListBotnets<TData = Awaited<ReturnType<typeof listBotnets>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listBotnets>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListBotnetsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getLookupIpReputationUrl = (params: LookupIpReputationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/ip-reputation?${stringifiedParams}` : `/api/ip-reputation`
}

/**
 * @summary Look up reputation for an IP address
 */
export const lookupIpReputation = async (params: LookupIpReputationParams, options?: RequestInit): Promise<IpReputation> => {

  return customFetch<IpReputation>(getLookupIpReputationUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLookupIpReputationQueryKey = (params?: LookupIpReputationParams,) => {
    return [
    `/api/ip-reputation`, ...(params ? [params] : [])
    ] as const;
    }


export const getLookupIpReputationQueryOptions = <TData = Awaited<ReturnType<typeof lookupIpReputation>>, TError = ErrorType<unknown>>(params: LookupIpReputationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof lookupIpReputation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLookupIpReputationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof lookupIpReputation>>> = ({ signal }) => lookupIpReputation(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lookupIpReputation>>, TError, TData> & { queryKey: QueryKey }
}

export type LookupIpReputationQueryResult = NonNullable<Awaited<ReturnType<typeof lookupIpReputation>>>
export type LookupIpReputationQueryError = ErrorType<unknown>


/**
 * @summary Look up reputation for an IP address
 */

export function useLookupIpReputation<TData = Awaited<ReturnType<typeof lookupIpReputation>>, TError = ErrorType<unknown>>(
 params: LookupIpReputationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof lookupIpReputation>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getLookupIpReputationQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







